apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mn2yj99tp-python 
  janus-idp.io/tekton: mn2yj99tp-python
  backstage.io/kubernetes-id: mn2yj99tp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mn2yj99tp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml