apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mn2yj99tp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mn2yj99tp-python 
  name: mn2yj99tp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mn2yj99tp-python 
